"""baseline

Revision ID: 0001
Revises:
Create Date: 2026-10-06 14:16:14.194852
"""

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_cache",
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("prompt_version", sa.String(), nullable=False),
        sa.Column("output_json", sa.Text(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("task", "key", "prompt_version", name=op.f("pk_ai_cache")),
    )
    op.create_table(
        "ai_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column("run_dir", sa.String(), nullable=False),
        sa.Column("n_items", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "status IN ('ok', 'partial', 'failed', 'limited')", name=op.f("ck_ai_runs_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_runs")),
    )
    op.create_table(
        "cards",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("issuer", sa.String(), nullable=False),
        sa.Column("product", sa.String(), nullable=False),
        sa.Column("network", sa.String(), nullable=False),
        sa.Column("card_type", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cards")),
    )
    op.create_table(
        "categories",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["categories.id"], name=op.f("fk_categories_parent_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
    )
    op.create_table(
        "people",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("full_name", sa.String(), nullable=False),
        sa.Column("relationship", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_people")),
    )
    op.create_table(
        "review_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("ref_table", sa.String(), nullable=True),
        sa.Column("ref_id", sa.String(), nullable=True),
        sa.Column("details_json", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.Column("resolved_at", sa.String(), nullable=True),
        sa.CheckConstraint(
            "kind IN ('unmatched_charge', 'unmatched_order_charge', 'unexpected_merchant', 'statement_mismatch', 'parse_failure', 'low_confidence', 'uncategorized', 'unknown_person', 'sync_gap')",
            name=op.f("ck_review_items_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('open', 'resolved', 'ignored')", name=op.f("ck_review_items_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_review_items")),
    )
    with op.batch_alter_table("review_items", schema=None) as batch_op:
        batch_op.create_index("ix_review_items_ref", ["kind", "ref_table", "ref_id"], unique=False)

    op.create_table(
        "sync_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("site", sa.String(), nullable=False),
        sa.Column("started_at", sa.String(), nullable=False),
        sa.Column("ended_at", sa.String(), nullable=True),
        sa.Column("since_date", sa.String(), nullable=True),
        sa.Column("until_date", sa.String(), nullable=True),
        sa.Column("run_dir", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("mode", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("files_imported", sa.Integer(), nullable=False),
        sa.Column("guard_blocks", sa.Integer(), nullable=False),
        sa.Column("report_json", sa.Text(), nullable=True),
        sa.CheckConstraint("mode IN ('approve', 'trusted')", name=op.f("ck_sync_runs_mode")),
        sa.CheckConstraint(
            "status IN ('running', 'ok', 'partial', 'failed', 'aborted')",
            name=op.f("ck_sync_runs_status"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_runs")),
    )
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_sync_runs_site"), ["site"], unique=False)

    op.create_table(
        "user_overrides",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(), nullable=False),
        sa.Column("stable_key", sa.String(), nullable=False),
        sa.Column("field", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "target_type IN ('transaction', 'order_item', 'merchant')",
            name=op.f("ck_user_overrides_target_type"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_overrides")),
        sa.UniqueConstraint(
            "target_type", "stable_key", "field", name=op.f("uq_user_overrides_target_type")
        ),
    )
    op.create_table(
        "card_holders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=False),
        sa.Column("card_ending", sa.String(), nullable=True),
        sa.Column("role", sa.String(), nullable=False),
        sa.CheckConstraint(
            "role IN ('primary', 'authorized_user')", name=op.f("ck_card_holders_role")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_card_holders_card_id_cards")
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_card_holders_person_id_people")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_card_holders")),
        sa.UniqueConstraint("card_id", "person_id", name=op.f("uq_card_holders_card_id")),
    )
    op.create_table(
        "imports",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sync_run_id", sa.Integer(), nullable=True),
        sa.Column("source", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=True),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("period_start", sa.String(), nullable=True),
        sa.Column("period_end", sa.String(), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("imported_at", sa.String(), nullable=False),
        sa.CheckConstraint(
            "kind IN ('transactions', 'statement', 'orders', 'receipts', 'emails')",
            name=op.f("ck_imports_kind"),
        ),
        sa.CheckConstraint(
            "status IN ('ok', 'partial', 'failed', 'skipped')", name=op.f("ck_imports_status")
        ),
        sa.ForeignKeyConstraint(["card_id"], ["cards.id"], name=op.f("fk_imports_card_id_cards")),
        sa.ForeignKeyConstraint(
            ["sync_run_id"], ["sync_runs.id"], name=op.f("fk_imports_sync_run_id_sync_runs")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_imports")),
        sa.UniqueConstraint("sha256", name=op.f("uq_imports_sha256")),
    )
    op.create_table(
        "merchants",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("merchant_group", sa.String(), nullable=True),
        sa.Column("default_category_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["default_category_id"],
            ["categories.id"],
            name=op.f("fk_merchants_default_category_id_categories"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_merchants")),
        sa.UniqueConstraint("name", name=op.f("uq_merchants_name")),
    )
    with op.batch_alter_table("merchants", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_merchants_merchant_group"), ["merchant_group"], unique=False
        )

    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("match_field", sa.String(), nullable=False),
        sa.Column("pattern", sa.String(), nullable=False),
        sa.Column("merchant_name", sa.String(), nullable=True),
        sa.Column("merchant_group", sa.String(), nullable=True),
        sa.Column("category_id", sa.String(), nullable=True),
        sa.Column("txn_type", sa.String(), nullable=True),
        sa.Column("created_by", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.CheckConstraint("created_by IN ('seed', 'user')", name=op.f("ck_rules_created_by")),
        sa.CheckConstraint(
            "match_field IN ('description_clean', 'description_raw', 'title_clean', 'title_raw')",
            name=op.f("ck_rules_match_field"),
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_rules_category_id_categories")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rules")),
    )
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("merchant", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("external_id", sa.String(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("order_date", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("subtotal", sa.Integer(), nullable=True),
        sa.Column("shipping", sa.Integer(), nullable=False),
        sa.Column("tax", sa.Integer(), nullable=False),
        sa.Column("discounts", sa.Integer(), nullable=False),
        sa.Column("gift_card_applied", sa.Integer(), nullable=False),
        sa.Column("total", sa.Integer(), nullable=False),
        sa.Column("raw_path", sa.String(), nullable=False),
        sa.CheckConstraint(
            "channel IN ('online', 'warehouse', 'digital')", name=op.f("ck_orders_channel")
        ),
        sa.ForeignKeyConstraint(
            ["import_id"], ["imports.id"], name=op.f("fk_orders_import_id_imports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("merchant", "external_id", name=op.f("uq_orders_merchant")),
    )
    op.create_table(
        "statements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=True),
        sa.Column("period_start", sa.String(), nullable=False),
        sa.Column("period_end", sa.String(), nullable=False),
        sa.Column("due_date", sa.String(), nullable=True),
        sa.Column("previous_balance", sa.Integer(), nullable=False),
        sa.Column("payments", sa.Integer(), nullable=False),
        sa.Column("credits", sa.Integer(), nullable=False),
        sa.Column("purchases", sa.Integer(), nullable=False),
        sa.Column("cash_advances", sa.Integer(), nullable=False),
        sa.Column("balance_transfers", sa.Integer(), nullable=False),
        sa.Column("fees", sa.Integer(), nullable=False),
        sa.Column("interest", sa.Integer(), nullable=False),
        sa.Column("new_balance", sa.Integer(), nullable=False),
        sa.Column("minimum_due", sa.Integer(), nullable=True),
        sa.Column("pdf_path", sa.String(), nullable=False),
        sa.Column("parse_method", sa.String(), nullable=False),
        sa.Column("math_ok", sa.Boolean(), nullable=False),
        sa.Column("ledger_status", sa.String(), nullable=True),
        sa.Column("ledger_delta_cents", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "ledger_status IS NULL OR ledger_status IN ('match', 'mismatch', 'incomplete')",
            name=op.f("ck_statements_ledger_status"),
        ),
        sa.CheckConstraint(
            "parse_method IN ('regex', 'ai', 'manual')", name=op.f("ck_statements_parse_method")
        ),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_statements_card_id_cards")
        ),
        sa.ForeignKeyConstraint(
            ["import_id"], ["imports.id"], name=op.f("fk_statements_import_id_imports")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statements")),
        sa.UniqueConstraint("card_id", "period_end", name=op.f("uq_statements_card_id")),
    )
    op.create_table(
        "order_charges",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("charge_date", sa.String(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("card_ending", sa.String(), nullable=True),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("raw_text", sa.String(), nullable=True),
        sa.CheckConstraint("kind IN ('charge', 'refund')", name=op.f("ck_order_charges_kind")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_charges_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_charges")),
    )
    op.create_table(
        "order_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("order_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(), nullable=True),
        sa.Column("seller", sa.String(), nullable=True),
        sa.Column("title_raw", sa.String(), nullable=False),
        sa.Column("title_clean", sa.String(), nullable=True),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("unit_price_cents", sa.Integer(), nullable=True),
        sa.Column("line_total_cents", sa.Integer(), nullable=False),
        sa.Column("discount_cents", sa.Integer(), nullable=False),
        sa.Column("taxable", sa.Boolean(), nullable=True),
        sa.Column("category_id", sa.String(), nullable=True),
        sa.Column("category_source", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_order_items_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
    )
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_order_items_sku"), ["sku"], unique=False)

    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("card_id", sa.String(), nullable=False),
        sa.Column("person_id", sa.String(), nullable=True),
        sa.Column("card_ending", sa.String(), nullable=True),
        sa.Column("txn_date", sa.String(), nullable=True),
        sa.Column("post_date", sa.String(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("description_raw", sa.String(), nullable=False),
        sa.Column("description_clean", sa.String(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("category_id", sa.String(), nullable=True),
        sa.Column("category_source", sa.String(), nullable=True),
        sa.Column("external_id", sa.String(), nullable=True),
        sa.Column("dedupe_key", sa.String(), nullable=False),
        sa.Column("import_id", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=True),
        sa.Column("review_status", sa.String(), nullable=False),
        sa.CheckConstraint(
            "category_source IS NULL OR category_source IN ('rule', 'ai', 'user', 'split')",
            name=op.f("ck_transactions_category_source"),
        ),
        sa.CheckConstraint(
            "review_status IN ('ok', 'needs_review', 'reviewed')",
            name=op.f("ck_transactions_review_status"),
        ),
        sa.CheckConstraint(
            "type IN ('purchase', 'payment', 'refund', 'credit', 'reward', 'fee', 'interest', 'adjustment')",
            name=op.f("ck_transactions_type"),
        ),
        sa.ForeignKeyConstraint(
            ["card_id"], ["cards.id"], name=op.f("fk_transactions_card_id_cards")
        ),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_transactions_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["import_id"], ["imports.id"], name=op.f("fk_transactions_import_id_imports")
        ),
        sa.ForeignKeyConstraint(
            ["merchant_id"], ["merchants.id"], name=op.f("fk_transactions_merchant_id_merchants")
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["people.id"], name=op.f("fk_transactions_person_id_people")
        ),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
            name=op.f("fk_transactions_statement_id_statements"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_transactions")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_transactions_dedupe_key")),
    )
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.create_index("ix_transactions_card_post", ["card_id", "post_date"], unique=False)

    op.create_table(
        "allocations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.String(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(), nullable=False),
        sa.CheckConstraint("source IN ('order_items', 'user')", name=op.f("ck_allocations_source")),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"], name=op.f("fk_allocations_category_id_categories")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_allocations_transaction_id_transactions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
    )
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_allocations_transaction_id"), ["transaction_id"], unique=False
        )

    op.create_table(
        "emails",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("gmail_id", sa.String(), nullable=False),
        sa.Column("from_addr", sa.String(), nullable=False),
        sa.Column("subject", sa.String(), nullable=True),
        sa.Column("sent_at", sa.String(), nullable=False),
        sa.Column("merchant", sa.String(), nullable=True),
        sa.Column("parsed_total_cents", sa.Integer(), nullable=True),
        sa.Column("parsed_json", sa.Text(), nullable=True),
        sa.Column("raw_path", sa.String(), nullable=False),
        sa.Column("linked_transaction_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["linked_transaction_id"],
            ["transactions.id"],
            name=op.f("fk_emails_linked_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_emails")),
        sa.UniqueConstraint("gmail_id", name=op.f("uq_emails_gmail_id")),
    )
    op.create_table(
        "matches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("transaction_id", sa.Integer(), nullable=False),
        sa.Column("order_charge_id", sa.Integer(), nullable=True),
        sa.Column("order_id", sa.Integer(), nullable=True),
        sa.Column("method", sa.String(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "method IN ('exact', 'window', 'ai', 'user')", name=op.f("ck_matches_method")
        ),
        sa.ForeignKeyConstraint(
            ["order_charge_id"],
            ["order_charges.id"],
            name=op.f("fk_matches_order_charge_id_order_charges"),
        ),
        sa.ForeignKeyConstraint(
            ["order_id"], ["orders.id"], name=op.f("fk_matches_order_id_orders")
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_matches_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_matches")),
        sa.UniqueConstraint("transaction_id", name=op.f("uq_matches_transaction_id")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("matches")
    op.drop_table("emails")
    with op.batch_alter_table("allocations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_allocations_transaction_id"))

    op.drop_table("allocations")
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index("ix_transactions_card_post")

    op.drop_table("transactions")
    with op.batch_alter_table("order_items", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_order_items_sku"))

    op.drop_table("order_items")
    op.drop_table("order_charges")
    op.drop_table("statements")
    op.drop_table("orders")
    op.drop_table("rules")
    with op.batch_alter_table("merchants", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_merchants_merchant_group"))

    op.drop_table("merchants")
    op.drop_table("imports")
    op.drop_table("card_holders")
    op.drop_table("user_overrides")
    with op.batch_alter_table("sync_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sync_runs_site"))

    op.drop_table("sync_runs")
    with op.batch_alter_table("review_items", schema=None) as batch_op:
        batch_op.drop_index("ix_review_items_ref")

    op.drop_table("review_items")
    op.drop_table("people")
    op.drop_table("categories")
    op.drop_table("cards")
    op.drop_table("ai_runs")
    op.drop_table("ai_cache")
    # ### end Alembic commands ###
