"""statement lines, order refs, person source

Revision ID: 0002
Revises: 0001
Create Date: 2026-10-06 19:54:25.686118
"""

import sqlalchemy as sa
from alembic import op

revision = "0002"
down_revision = "0001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "statement_lines",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column("line_no", sa.Integer(), nullable=False),
        sa.Column("section", sa.String(), nullable=False),
        sa.Column("txn_date", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("order_ref", sa.String(), nullable=True),
        sa.Column("cardholder_name", sa.String(), nullable=True),
        sa.Column("transaction_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
            name=op.f("fk_statement_lines_statement_id_statements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["transaction_id"],
            ["transactions.id"],
            name=op.f("fk_statement_lines_transaction_id_transactions"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_statement_lines")),
    )
    with op.batch_alter_table("statement_lines", schema=None) as batch_op:
        batch_op.create_index(
            "ix_statement_lines_match", ["statement_id", "txn_date", "amount_cents"], unique=False
        )

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("payment_method", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("payment_card_ending", sa.String(), nullable=True))

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("person_source", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("order_ref", sa.String(), nullable=True))
        batch_op.create_index(batch_op.f("ix_transactions_order_ref"), ["order_ref"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_transactions_order_ref"))
        batch_op.drop_column("order_ref")
        batch_op.drop_column("person_source")

    with op.batch_alter_table("orders", schema=None) as batch_op:
        batch_op.drop_column("payment_card_ending")
        batch_op.drop_column("payment_method")

    with op.batch_alter_table("statement_lines", schema=None) as batch_op:
        batch_op.drop_index("ix_statement_lines_match")

    op.drop_table("statement_lines")
    # ### end Alembic commands ###
