"""import file kind, transaction source

Revision ID: 0003
Revises: 0002
Create Date: 2026-10-06 22:16:18.535861
"""

import sqlalchemy as sa
from alembic import op

revision = "0003"
down_revision = "0002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.add_column(sa.Column("file_kind", sa.String(), nullable=True))

    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("source", sa.String(), nullable=False, server_default="csv"))

    # ### end Alembic commands ###

    # Existing imports predate file_kind: transactions and statement keep their kind; orders
    # were all Amazon printable invoices.
    op.execute(
        "UPDATE imports SET file_kind = CASE kind WHEN 'orders' THEN 'order_invoice' ELSE kind END "
        "WHERE file_kind IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("transactions", schema=None) as batch_op:
        batch_op.drop_column("source")

    with op.batch_alter_table("imports", schema=None) as batch_op:
        batch_op.drop_column("file_kind")

    # ### end Alembic commands ###
