"""standalone order charges

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-06 22:42:11.840669
"""

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_charges", schema=None) as batch_op:
        batch_op.add_column(sa.Column("merchant", sa.String(), nullable=False, server_default="amazon"))
        batch_op.add_column(sa.Column("order_ref", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("import_id", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("card_name", sa.String(), nullable=True))
        batch_op.add_column(sa.Column("dedupe_key", sa.String(), nullable=True))
        batch_op.alter_column("order_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.create_index(batch_op.f("ix_order_charges_order_ref"), ["order_ref"], unique=False)
        batch_op.create_unique_constraint(batch_op.f("uq_order_charges_dedupe_key"), ["dedupe_key"])
        batch_op.drop_constraint(batch_op.f("fk_order_charges_order_id_orders"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_order_charges_order_id_orders"),
            "orders",
            ["order_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_order_charges_import_id_imports"), "imports", ["import_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("order_charges", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_order_charges_import_id_imports"), type_="foreignkey"
        )
        batch_op.drop_constraint(batch_op.f("fk_order_charges_order_id_orders"), type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_order_charges_order_id_orders"),
            "orders",
            ["order_id"],
            ["id"],
            ondelete="CASCADE",
        )
        batch_op.drop_constraint(batch_op.f("uq_order_charges_dedupe_key"), type_="unique")
        batch_op.drop_index(batch_op.f("ix_order_charges_order_ref"))
        batch_op.alter_column("order_id", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_column("dedupe_key")
        batch_op.drop_column("card_name")
        batch_op.drop_column("import_id")
        batch_op.drop_column("order_ref")
        batch_op.drop_column("merchant")

    # ### end Alembic commands ###
